### ISSUE TITLE
Uploading 38 Move files is causing server to disconnect

### ISSUE THREAD

**Issue by palmbri** [EPPIcenter/sampleDB-rpackage#2]
Currently, the user can upload move files from their local pc to sample db. In one instance, a 38 file upload was attempted, which resulted in server disconnection.

Expected behavior is that the server will not disconnect for any number of file uploads.

**Comment by smaxfield** [comment]
After renaming all plates in SampleDB to remove spaces (matching CSV file names), closing and reopening SampleDB, I am receiving a "move failed due to error" message.

<img width="375" alt="Screen Shot 2022-06-23 at 12 00 20 PM" src="https://user-images.githubusercontent.com/108092495/175377469-272c54b5-98d2-494b-b357-d55be6788385.png">


[New Move File CSVs.zip](https://github.com/EPPIcenter/sampleDB-rpackage/files/8970195/New.Move.File.CSVs.zip)

**Comment by palmbri** [comment]
Move files uploaded after adding missing samples and fixing plate name
