### ISSUE TITLE
Move went through despite me forgetting to attach one of the plates. Orphaned samples mysteriously moved to plate 101

### ISSUE THREAD

**Issue by jovinden** [EPPIcenter/sampleDB-rpackage#54]
I did a sample move with these files: 
[SeroX Plate 10_20220718_131435.csv](https://github.com/EPPIcenter/sampleDB-rpackage/files/9135928/SeroX.Plate.10_20220718_131435.csv)
[SeroX Plate 17_20220718_131539.csv](https://github.com/EPPIcenter/sampleDB-rpackage/files/9135929/SeroX.Plate.17_20220718_131539.csv)
[SeroX_022_20220718_131635.csv](https://github.com/EPPIcenter/sampleDB-rpackage/files/9135930/SeroX_022_20220718_131635.csv)
[SeroX Plate 20_20220718_133243.csv](https://github.com/EPPIcenter/sampleDB-rpackage/files/9135931/SeroX.Plate.20_20220718_133243.csv)

Forgetting to attach 
[SeroX Plate 16_20220718_142828.csv](https://github.com/EPPIcenter/sampleDB-rpackage/files/9135932/SeroX.Plate.16_20220718_142828.csv)

The move went through, when it should have stopped and notified me of sample being orphaned. The samples that were supposed to be on SeroX Plate 16 were relocated to Plate 101
![image (13)](https://user-images.githubusercontent.com/61671020/179622532-ec59fe9d-6bb8-4690-83a3-5579b67d5577.png)

I was able to move them to SeroX Plate 16 by doing a move with only that file attached.

**Comment by palmbri** [comment]
![Screenshot from 2022-07-18 16-43-40](https://user-images.githubusercontent.com/103962129/179635012-79f9323b-4677-4528-bd18-c2ae2f3abb6e.png)
[sampledb-17:55:31_13-07-2022.sqlite.gz](https://github.com/EPPIcenter/sampleDB-rpackage/files/9136299/sampledb-17.55.31_13-07-2022.sqlite.gz)

Looks like this is a remnant of the move problem from a week ago, and the mysterious move caused by a possible bug in the algorithm:

```R
      for(i in 1:nrow(sample_data.existing_container)) {
        state <- sample_data.existing_container[i,]$state_id
        if (!is.na(state) && !is_empty(state) && state == 1) {
          id <- sample_data.existing_container[i,]$id
          ModifyTable(conn = conn,
                      table_name = "matrix_tube",
                      info_list = list(plate_id = -(i)),
                      id = id) %>% suppressWarnings()
          }
      }
```
It's pretty clever to negate the plate id, but we don't explicitly do that; we negate the row id instead. In backups prior to this one, this sample is on SeroX plate 16, but now it is on -3. It would make more sense for the plate id to just be negated since we have that information available already and there should be no unique constraint on that column. 

As for ending up on plate 101, that is partially my fault because I thought you could just reinvert the plate id - the plate id for plate 101 is 3.

**Comment by palmbri** [comment]
Yeah that's similar to what I was thinking needs to be done, we just need to keep sample information where possible which is not being done currently. I'll swap out the plate id negation with well position negation which seems to be what you did.
